# .readthedocs.yml
# 配置文件版本，必须为 2
version: 2

# 指定构建环境和工具版本
build:
  os: ubuntu-22.04  # 构建系统
  tools:
    python: "3.11"   # Python版本，建议3.7或更高[citation:1][citation:2][citation:3]

# 指定使用 MkDocs 及主配置文件
mkdocs:
  configuration: mkdocs.yml  # MkDocs配置文件名
  
# 关键：声明需要安装的Python依赖
python:
  install:
    - requirements: requirements.txt  # 方式一：推荐，通过文件管理依赖
    # 或直接指定包
    # - method: pip
    #   path: .
    #   extra_requirements:
    #     - docs